### PR TITLE
Add command log

### PR DESCRIPTION
**Pull request by CJWess**
@fawwaazbadar

### CODE REVIEW

**Comment by CJWess** [comment]
yo do you wanna hop back in that same hangout and finish up?

**Comment by fawwaazbadar** [comment]
hey man I actually have to wait about 1 hour half till I can, how do u want
to do this?

**Comment by CJWess** [comment]
That's fine with me, man.. ideally we'd just use the same hangouts call. Go
ahead and send me a message on slack or here when you're ready

**Comment by CJWess** [comment]
We do have to finish it tonight though, as I'm pretty sure it's due by 10am
tomorrow

**Comment by fawwaazbadar** [comment]
ok I'll do that

**Comment by CJWess** [comment]
you around man? still gotta finish this.

**Comment by fawwaazbadar** [comment]
hey man I apologize, I will be at 12 am pst. if that's too late, early
tomorrow morning we can get it done. i'll be online checking email

**Comment by CJWess** [comment]
yo if you have time now, I have a bit before work to finish up

**Pull request merged**
